name: Deploy to Railway
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Test results
        if: success()
        run: echo "✅ All tests passed!"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy to Railway
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy to Railway
        run: |
          railway login --browserless
          railway link --project=${{ secrets.RAILWAY_PROJECT_ID }}
          railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
      - name: Deployment success
        if: success()
        run: echo "🚀 Deployment completed successfully!"